[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy>=1.20.2",
    "pandas>=1.2.4",
    "matplotlib>=3.4.2",
    "networkx>=2.5.1",
    "torch>=1.8.1"
]
build-backend = "setuptools.build_meta"